### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by panvagenas** [bonny/WordPress-Admin-Menu-Tree-Page-View#2]
Hi, 

Please provide me a secure channel in order to send a report about a security vulnerability in this plugin. I also tried to contact the author through wordpress.org support forums with no luck.

Thanks,
Pan

**Comment by bonny** [comment]
Hi, please send me an email to the adress in my profile: https://github.com/bonny

**Comment by 1ucay** [comment]
Plugin dont check cap in function! Please update asap!
